### ISSUE TITLE
[Bug] ImageTooltip in the playground doesn't update the DOM

### ISSUE THREAD

**Issue by granmoe** [Milkdown/website#24]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Milkdown Playground v.7.2.3

### Link to runnable example

https://milkdown.dev/playground

### Steps to reproduce

First, thank you for creating such an amazing editor framework! I'm a sponsor 🙂

Visit the [Milkdown Playground](https://milkdown.dev/playground). Click the image and edit any attribute. Close the tooltip.

### Expected behavior

Edited attributes should update the editor state and DOM.

### Actual behavior

No changes are made. Also, sometimes the values in the popover disappear.

I really want this to work because I want to use tooltip plugins to allow users to edit links and images!

### Runtime

Chrome

### OS

macOS

**Comment by ZhenlyChen** [comment]
https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/ImageTooltip.tsx#L27
When I change this line to the following code, it will work fine.
```
 appendTo: document.querySelector('.milkdown')!,
```

**Comment by granmoe** [comment]
Thanks, but I ended up switching to Tiptap in the meantime because it fit my needs better
