### ISSUE TITLE
Documentation Version

### ISSUE THREAD

**Issue by omerharuncetin** [Milkdown/website#3]
I have a suggestion about documentation website.

We should also see documentation for older versions too. Because currently I'm using the **6.3** version for milkdown and current milkdown documentation website only supports **7.0**. Thus, I'm not able to find the documentation that I'm looking for.

**Comment by Saul-Mirone** [comment]
You can find the legacy doc at https://milkdown-git-v6-saul-mirone.vercel.app/, but it'll be removed someday.
