### ISSUE TITLE
doc website out of memory

### ISSUE THREAD

**Issue by fall-zhang** [Milkdown/website#39]
![2024-06-04 142850](https://github.com/Milkdown/website/assets/62327825/4b21cd3b-5517-4245-99d3-3587bbbc4676)
![2024-06-04 143047](https://github.com/Milkdown/website/assets/62327825/38c8b9e2-9884-4d52-9fb7-3fe917ed95f5)

browser: chrome
OS: windows 11

open doc website, change the menu, waiting about 5min,

![2024-06-04 144221](https://github.com/Milkdown/website/assets/62327825/262e1402-54fb-4016-8818-dcc33843bee6)

![image](https://github.com/Milkdown/website/assets/62327825/2ced8a82-f566-448f-bd7e-d9ff093ee6cf)

![image](https://github.com/Milkdown/website/assets/62327825/b7996659-0d41-40b1-9977-d63ac79ba131)

**Comment by Saul-Mirone** [comment]
Fixed
